USER-SERVER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true
testfool: 5201314
server: 
  port: 8742
spring: 
  application:
    name: api-server
