spring:
  application:
    name: api-server

server:
  port: 8742

eureka:
  client:
    register-with-eureka: true   #false表示不向注册中心注册自己。
    fetch-registry: true      #false表示自己是注册中心，职责是维护服务，而不是调用服务
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/

USER-SERVER:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true
